name: Github Actions Demo
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu:latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install -e .

      - name: Lint with flake8
        run:
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test with Python script
        run: python main.py --test